language: node_js

node_js:
  - node
  - 12
  - 10
  - 8

script:
  - npm run build
  - npm test
  - npm run lint

matrix:
  fast_finish: true
  include:
    - language: python
      python: 3.7
      before_script:
        - pip install pre-commit
      script:
        - pre-commit run --all-files --show-diff-on-failure --config .travis-pre-commit-config.yaml
