on:
  - push
  - pull_request

name: Main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '10'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: |
          npm install
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '10'
          - '12'
          - '14'
    name: test (node = ${{ matrix.node-version }})
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build
          npm run test
          npm run docs
